import {useEffect,useState} from 'react'
import {Outlet,NavLink,Link,useLocation} from 'react-router-dom'
import {LayoutDashboard,Package,PanelsTopLeft,ShoppingCart,MessageSquare,LogOut,ExternalLink,Menu,X,ArrowUpRight} from 'lucide-react'
import {useAuth} from '../../hooks/useAuth'
import {useData} from '../../hooks/useData'
import {ToastProvider} from '../shared/Toast'
import '../../admin.css'
const nav=[['/admin','Overview',LayoutDashboard],['/admin/content','Website studio',PanelsTopLeft],['/admin/products','Products',Package],['/admin/orders','Product enquiries',ShoppingCart],['/admin/messages','Messages',MessageSquare]]
export default function AdminLayout(){const {user,logout}=useAuth();const {site,dataError}=useData();const [open,setOpen]=useState(false);const {pathname}=useLocation();useEffect(()=>setOpen(false),[pathname]);useEffect(()=>{document.title='Website studio | Joytun';let m=document.querySelector('meta[name="robots"]');if(!m){m=document.createElement('meta');m.name='robots';document.head.append(m)}m.content='noindex,nofollow'},[])
return <ToastProvider><div className="admin-shell">{open&&<button className="admin-scrim" aria-label="Close navigation" onClick={()=>setOpen(false)}/>}<aside className={`admin-sidebar ${open?'is-open':''}`}><Link to="/admin" className="admin-brand"><span>J<span>.</span></span><div>JOYTUN<small>WEBSITE STUDIO</small></div></Link><button className="admin-close" onClick={()=>setOpen(false)} aria-label="Close navigation"><X/></button><p className="sidebar-caption">WORKSPACE</p><nav aria-label="Admin navigation">{nav.map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/admin'}><Icon size={19}/>{label}</NavLink>)}</nav><div className="sidebar-help"><span className="small-dot"/><p>Your brand.<br/>Every detail, in your hands.</p><Link to="/" target="_blank" rel="noreferrer">View live website <ArrowUpRight size={17}/></Link></div><div className="admin-account"><div className="account-avatar">{(user?.displayName||user?.email||'J')[0].toUpperCase()}</div><div><strong>{user?.displayName||'Administrator'}</strong><small>Administrator</small></div><button onClick={logout} aria-label="Sign out"><LogOut size={17}/></button></div></aside><div className="admin-workspace"><header className="admin-topbar"><button className="admin-menu" aria-label="Open navigation" onClick={()=>setOpen(true)}><Menu/></button><span>{site.brand.name}</span><div><span className="connection-status">{dataError?'Connection interrupted':'Content workspace'}</span><Link to="/" target="_blank" rel="noreferrer">Open website <ExternalLink size={14}/></Link></div></header><main className="admin-main"><Outlet/></main><footer className="admin-footer">Joytun Website Studio <span>Carefully made. Confidently managed.</span></footer></div></div></ToastProvider>}
