import {useState} from 'react'
import {Mail,Inbox,Search,Phone,ChevronDown,ChevronUp} from 'lucide-react'
import {useData} from '../../hooks/useData'
import {useToast} from '../../components/shared/Toast'
import {updateEnquiryStatus} from '../../lib/firestore'
export default function AdminInbox({kind='messages'}){
 const data=useData(),notify=useToast();const rows=data[kind],isOrder=kind==='orders';const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[expanded,setExpanded]=useState(null),[saving,setSaving]=useState('')
 const shown=rows.filter(r=>(filter==='all'||(r.status||'new')===filter)&&`${r.name} ${r.email} ${r.product||r.subject||''} ${r.msg||''}`.toLowerCase().includes(query.toLowerCase()))
 async function update(row,status){setSaving(row.id);try{await updateEnquiryStatus(kind,row.id,status);notify('Conversation status updated.')}catch{notify('Could not update status.','error')}finally{setSaving('')}}
 return <><div className="admin-page-heading"><div><p className="admin-eyebrow">CUSTOMER CONVERSATIONS</p><h1>{isOrder?'Product enquiries.':'Every hello matters.'}</h1><p>{isOrder?'Review product interest, requested quantities and customer details.':'Manage messages from your website and keep track of the next step.'}</p></div><span className="status-pill">{rows.filter(r=>!r.status||r.status==='new').length} new</span></div><div className="admin-filter-bar"><label><Search size={18}/><input aria-label="Search conversations" placeholder="Search name, email or enquiry" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filter by conversation status" value={filter} onChange={e=>setFilter(e.target.value)}>{['all','new','in-progress','resolved'].map(s=><option key={s} value={s}>{s==='all'?'All conversations':s}</option>)}</select></div><div className="inbox-list">{shown.map(row=><article className="admin-panel" key={row.id}><div className="inbox-heading"><button aria-expanded={expanded===row.id} onClick={()=>setExpanded(expanded===row.id?null:row.id)}><span className="inbox-avatar">{(row.name||'J')[0]}</span><div><strong>{row.name}</strong><p>{isOrder?row.product:row.subject||'General enquiry'}</p></div>{expanded===row.id?<ChevronUp size={18}/>:<ChevronDown size={18}/>}</button><select aria-label={`Status for ${row.name}`} disabled={saving===row.id} value={row.status||'new'} onChange={e=>update(row,e.target.value)}><option value="new">New</option><option value="in-progress">In progress</option><option value="resolved">Resolved</option></select></div>{expanded===row.id&&<div className="inbox-detail"><div><span><Mail size={15}/>{row.email||'Email not supplied'}</span><span><Phone size={15}/>{row.phone}</span></div>{isOrder?<dl><dt>Product / variant</dt><dd>{row.product} · {row.variant}</dd><dt>Requested quantity</dt><dd>{row.qty}</dd><dt>Customer location</dt><dd>{row.address}</dd></dl>:<p className="inbox-message">{row.msg}</p>}<small>{row.createdAt?.toDate?.().toLocaleString()||'Recently received'}</small></div>}</article>)}</div>{!shown.length&&<div className="admin-panel admin-empty"><Inbox size={32}/><h3>No conversations here yet.</h3><p>{rows.length?'Try a different search or status.':'Website enquiries will appear here when received.'}</p></div>}</>
}
