import { useEffect, useRef, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { ArrowUp, ArrowDown, Plus, Trash2, Save, Eye, RotateCcw, CheckCircle2, AlertCircle } from 'lucide-react'
import { useData } from '../../hooks/useData'
import { useToast } from '../../components/shared/Toast'
import { defaultSite, mergeSite, validateSite, LOCATION } from '../../data/site'
const groups=[['brand','Brand & contact'],['navigation','Navigation'],['home','Home page'],['slides','Hero collections'],['categories','Care categories'],['products','Catalogue page'],['about','Our story'],['values','Our purpose'],['contact','Contact page'],['faqs','FAQs'],['partner','Partnership banner'],['appearance','Design system'],['seo','Search & sharing']]
const labels={ink:'Primary text & buttons',green:'Accent text',lime:'Highlight color',paper:'Page background',headingFont:'Heading typeface',bodyFont:'Body typeface',motion:'Enable motion',radius:'Corner radius',url:'Link destination',buttonUrl:'Button destination',shortName:'Short brand name',subtitle:'Logo subtitle',location:'Company location',showBrands:'Show brand section',showCategories:'Show categories',showFeatured:'Show featured products',showRitual:'Show featured story',showStory:'Show company story',showPurpose:'Show purpose section',indexable:'Allow search engines to index public pages',cat:'Product category label',id:'Category ID',status:'Visibility',image:'Image',images:'Product images',featured:'Featured products',ritualImages:'Featured story images',revision:'Revision'}
const label=key=>labels[key]||key.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase())
const colorKeys=new Set(['ink','green','lime','paper','color'])
const longKeys=/description|text|title|paragraph|intro|lead|note|answer|usage|mission|vision|announcement|caption|accent/i
function Field({name,value,onChange,path,products,template}){
  if(name==='revision')return null
  if(name==='location')return <div className="editor-field"><span>Company location</span><p className="fixed-location">{LOCATION}</p><small>The single approved location used throughout the website.</small></div>
  if(typeof value==='boolean')return <label className="editor-switch"><span>{label(name)}</span><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/></label>
  if(name==='sectionOrder')return <fieldset className="editor-array"><legend>Homepage section order</legend><p className="admin-help">Move sections into the order you want visitors to see.</p>{value.map((v,i)=><div className="array-toolbar" key={v}><span>{label(v)}</span><div><button type="button" aria-label={`Move ${v} up`} disabled={!i} onClick={()=>{const copy=[...value];[copy[i-1],copy[i]]=[copy[i],copy[i-1]];onChange(copy)}}><ArrowUp size={15}/></button><button type="button" aria-label={`Move ${v} down`} disabled={i===value.length-1} onClick={()=>{const copy=[...value];[copy[i+1],copy[i]]=[copy[i],copy[i+1]];onChange(copy)}}><ArrowDown size={15}/></button></div></div>)}</fieldset>
  if(Array.isArray(value)){
    const primitive=value.every(v=>typeof v==='string')
    const productList=['images','featured','ritualImages'].includes(name)
    return <fieldset className="editor-array"><legend>{label(name)}</legend>{value.map((item,i)=><div className="editor-array-item" key={i}><div className="array-toolbar"><span>{String(i+1).padStart(2,'0')} {item?.name||item?.label||item?.question||''}</span><div><button type="button" aria-label={`Move ${label(name)} item ${i+1} up`} disabled={!i} onClick={()=>{const copy=[...value];[copy[i-1],copy[i]]=[copy[i],copy[i-1]];onChange(copy)}}><ArrowUp size={15}/></button><button type="button" aria-label={`Move ${label(name)} item ${i+1} down`} disabled={i===value.length-1} onClick={()=>{const copy=[...value];[copy[i+1],copy[i]]=[copy[i],copy[i+1]];onChange(copy)}}><ArrowDown size={15}/></button><button type="button" aria-label={`Remove ${label(name)} item ${i+1}`} onClick={()=>onChange(value.filter((_,j)=>j!==i))}><Trash2 size={15}/></button></div></div>{primitive?(productList?<label className="editor-field"><span>Product</span><select value={item} onChange={e=>onChange(value.map((v,j)=>j===i?e.target.value:v))}><option value="">Choose a product</option>{products.map(p=><option key={p.id} value={p.slug||p.id}>{p.name} · {p.variant} · {p.format}</option>)}</select></label>:<input aria-label={`${label(name)} ${i+1}`} value={item} onChange={e=>onChange(value.map((v,j)=>j===i?e.target.value:v))}/>):<Fields value={item} path={`${path}.${i}`} products={products} template={template?.[0]} onChange={next=>onChange(value.map((v,j)=>j===i?next:v))}/>}</div>)}<button type="button" className="admin-button secondary small" onClick={()=>{const sample=template?.[0]??value[0];const fresh=sample&&typeof sample==='object'?Object.fromEntries(Object.entries(sample).map(([k,v])=>[k,Array.isArray(v)?[]:typeof v==='boolean'?v:typeof v==='number'?v:colorKeys.has(k)?v:k==='status'?'draft':''])):'';onChange([...value,fresh])}}><Plus size={15}/> Add {label(name).toLowerCase().replace(/s$/,'')}</button></fieldset>
  }
  if(value&&typeof value==='object')return <fieldset className="editor-object"><legend>{label(name)}</legend><Fields value={value} onChange={onChange} path={path} products={products} template={template}/></fieldset>
  const selectOptions=name==='status'?['active','draft']:name==='headingFont'||name==='bodyFont'?['Manrope','DM Sans']:null
  return <label className={`editor-field ${longKeys.test(name)?'wide':''}`}><span>{label(name)}</span>{selectOptions?<select value={value} onChange={e=>onChange(e.target.value)}>{selectOptions.map(x=><option key={x}>{x}</option>)}</select>:name==='image'&&path.startsWith('categories')?<select value={value} onChange={e=>onChange(e.target.value)}>{products.map(p=><option key={p.id} value={p.slug||p.id}>{p.name} · {p.variant}</option>)}</select>:colorKeys.has(name)?<div className="color-field"><input aria-label={`${label(name)} picker`} type="color" value={/^#[a-f\d]{6}$/i.test(value)?value:'#ffffff'} onChange={e=>onChange(e.target.value)}/><input value={value} onChange={e=>onChange(e.target.value)}/></div>:typeof value==='number'?<input type="number" min="0" max="32" value={value} onChange={e=>onChange(Number(e.target.value))}/>:longKeys.test(name)?<textarea rows={name.toLowerCase().includes('title')?2:3} value={value??''} onChange={e=>onChange(e.target.value)}/>:<input type={name==='email'?'email':'text'} value={value??''} onChange={e=>onChange(e.target.value)}/>}{['url','buttonUrl','ritualLink'].includes(name)&&<small>Use a website path such as /products or a full HTTPS link.</small>}{['logo','favicon','image'].includes(name)&&!path.startsWith('categories')&&<small>Use an image URL or an existing /images/ path.</small>}</label>
}
function Fields({value,onChange,path='',products,template}){return <div className="editor-fields">{Object.entries(value).map(([k,v])=><Field key={k} name={k} value={v} products={products} template={template?.[k]} path={path?`${path}.${k}`:k} onChange={next=>onChange({...value,[k]:next})}/>)}</div>}
export default function AdminEditor({initialGroup}){
 const {site,products,settingsLoaded,updateSite,dataError}=useData();const notify=useToast();const [params,setParams]=useSearchParams()
 const group=initialGroup||params.get('section')||'home';const chosen=groups.some(([k])=>k===group)?group:'home'
 const [draft,setDraft]=useState(site),[baseRevision,setBaseRevision]=useState(site.revision),[saving,setSaving]=useState(false),[draftSaved,setDraftSaved]=useState(false)
 const touched=useRef(false)
 useEffect(()=>{if(!touched.current){setDraft(site);setBaseRevision(site.revision)}},[site])
 const dirty=JSON.stringify(draft)!==JSON.stringify(site)
 useEffect(()=>{if(!dirty)return;const warn=e=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty])
 const change=next=>{touched.current=true;setDraft(next);setDraftSaved(false)}
 async function publish(){const error=validateSite(draft);if(error)return notify(error,'error');setSaving(true);try{await updateSite(draft,baseRevision);touched.current=false;setBaseRevision(baseRevision+1);setDraft({...draft,revision:baseRevision+1});localStorage.removeItem('joytun-editor-draft');notify('Website published successfully.')}catch(e){notify(e.message||'Could not publish. Your changes are still here.','error')}finally{setSaving(false)}}
 function saveDraft(){try{localStorage.setItem('joytun-editor-draft',JSON.stringify({site:draft,revision:baseRevision}));setDraftSaved(true);notify('Draft saved in this browser.')}catch{notify('Browser storage is unavailable. Keep this tab open.','error')}}
 function restore(){try{const saved=JSON.parse(localStorage.getItem('joytun-editor-draft'));if(!saved)return notify('No saved draft in this browser.','error');change(mergeSite(saved.site));setBaseRevision(saved.revision)}catch{notify('This draft could not be loaded.','error')}}
 function preview(){localStorage.setItem('joytun-preview',JSON.stringify(draft));window.open((chosen==='about'?'/about':chosen==='contact'||chosen==='faqs'?'/contact':chosen==='products'||chosen==='categories'?'/products':'/')+'?preview=1','_blank','noopener,noreferrer')}
 return <div className="content-editor"><div className="admin-page-heading"><div><p className="admin-eyebrow">WEBSITE STUDIO</p><h1>Make it your own.</h1><p>Edit the website, preview your changes, then publish when ready.</p></div><span className={`status-pill ${dirty?'pending':''}`}>{dirty?'Unpublished changes':`Published · v${site.revision}`}</span></div>
 <div className="editor-actions"><div><button className="admin-button secondary" onClick={saveDraft}><Save size={16}/>{draftSaved?'Draft saved':'Save draft'}</button><button className="admin-button secondary" onClick={preview}><Eye size={16}/>Preview</button></div><button className="admin-button" onClick={publish} disabled={!dirty||saving||!settingsLoaded||!!dataError}><CheckCircle2 size={17}/>{saving?'Publishing…':'Publish changes'}</button></div>
 {dataError&&<p className="admin-alert" role="alert">{dataError} Publishing is paused until the connection recovers.</p>}{dirty&&site.revision!==baseRevision&&<p className="admin-alert" role="alert">Another session published a newer version. Save your draft, then reload the published version before editing.</p>}
 <div className="editor-layout"><nav className="editor-nav" aria-label="Website sections">{groups.map(([key,name])=><button key={key} className={chosen===key?'selected':''} onClick={()=>{if(initialGroup)window.location.assign(`/admin/content?section=${key}`);else setParams({section:key})}}>{name}<span>↗</span></button>)}</nav><section className="editor-panel"><div className="editor-panel-heading"><div><p className="admin-eyebrow">CONTENT & SETTINGS</p><h2>{groups.find(([key])=>key===chosen)?.[1]}</h2></div></div>{Array.isArray(draft[chosen])?<Field name={chosen} value={draft[chosen]} path={chosen} template={defaultSite[chosen]} products={products} onChange={v=>change({...draft,[chosen]:v})}/>:<Fields value={draft[chosen]} path={chosen} template={defaultSite[chosen]} products={products} onChange={v=>change({...draft,[chosen]:v})}/>}</section></div>
 <div className="editor-recovery"><button onClick={restore}><RotateCcw size={14}/> Restore browser draft</button><button onClick={()=>{if(dirty&&!confirm('Discard unpublished changes and reload the published version?'))return;touched.current=false;setDraft(site);setBaseRevision(site.revision)}}>Reload published version</button></div></div>
}
